function result = checkMonotonicityConsistency_v001(xGrid, yReplicates, betaObs, params)
%CHECKMONOTONICITYCONSISTENCY_V001 Empirical, replicate-based confidence
% that betaObs is locally recoverable -- no analytic noise/SE formula,
% no bootstrap synthesis. Uses the N_REPS INDEPENDENT, REAL replicate
% curve realisations already generated by the simulation directly.
%
% RATIONALE (2026-08-11): the classical monotonicity-testing literature
% (Hall & Heckman 2000; Bowman, Jones & Gijbels 1998; Ghosal, Sen & van
% der Vaart 2000 -- see docs/FINDINGS_REFERENCE.md Finding #154 for the
% literature review, and the actively-maintained R package
% MonotonicityTest, CRAN 2025, for a working reference implementation of
% Hall & Heckman) all solve a HARDER problem than this project actually
% has: they synthesise a null distribution via kernel-bandwidth-based
% residual bootstrap because they assume access to only ONE noisy curve.
% This project's own simulation already generates N_REPS independent,
% genuinely random realisations of the whole candidate curve (not
% synthetic bootstrap draws) -- res.betaRec, N_REPS x nPipelines x
% N_BETA. Using them directly sidesteps kernel-bandwidth selection and
% every free parameter the classical tests need to work around not
% having real replicates, and avoids the exact class of analytic-formula
% error made twice already this session (findBothBranches_v005's
% degenerate MDC-as-detection-threshold collapse; v007's corrected but
% still grid-dependent significance formula, which made the sensitivity
% WORSE by construction, sigma_slope ~ 1/dx).
%
% METHOD: apply findBothBranches_v004 (grid-invariant width-based
% smoothing/segment-floor, flat slopeTol -- the one part of this whole
% investigation that has NOT needed revision) to EACH of the N_REPS
% replicate curves independently. For each replicate, check whether
% betaObs falls inside any qualifying segment. The FRACTION of replicates
% where it does is a direct, empirical, distribution-free confidence that
% the apparent local monotonicity survives real repeated noise draws of
% the actual generative process -- not an estimate of anything, an
% observed frequency.
%
% SYNTAX:
%   result = checkMonotonicityConsistency_v001(xGrid, yReplicates, betaObs, params)
%
% INPUTS:
%   xGrid       -- 1 x N_BETA, the beta_gen sweep grid
%   yReplicates -- N_REPS x N_BETA, ALL replicate draws of beta_rec at
%                  each grid point (res.betaRec(:,pp,:) squeezed, for one
%                  pipeline)
%   betaObs     -- scalar, this trial's own observed value to check
%   params      -- same fields as findBothBranches_v004: smoothWidth,
%                  minSegWidth, slopeTol
%
% OUTPUT (struct):
%   result.fracCovered   -- fraction of replicates where betaObs fell in
%                            a qualifying segment (0 to 1)
%   result.nCovered      -- count version of the above
%   result.nReps         -- N_REPS actually used (rows of yReplicates)
%   result.perRepCovered -- N_REPS x 1 logical, per-replicate detail
%
% See also: findBothBranches_v004 (the per-replicate segment finder this
% wraps, unchanged); docs/FINDINGS_REFERENCE.md Finding #154 (literature
% review and validation this implements) and #155 (this function's own
% test against the grid-density-sensitivity benchmark)
%
% Fraser, D.S. (2026)

nReps = size(yReplicates, 1);
perRepCovered = false(nReps, 1);

for r = 1:nReps
    yRep = yReplicates(r, :);
    good = ~isnan(yRep);
    if nnz(good) < 2, continue, end

    both = findBothBranches_v004(xGrid(good), yRep(good), params);
    allRuns = [both.rise, both.desc];
    for k = 1:numel(allRuns)
        if betaObs >= min(allRuns(k).y) - eps && betaObs <= max(allRuns(k).y) + eps
            perRepCovered(r) = true;
        end
    end
end

result.fracCovered   = mean(perRepCovered);
result.nCovered      = sum(perRepCovered);
result.nReps         = nReps;
result.perRepCovered = perRepCovered;

end
