function trials = importDB_hickman_v001(opts)
% importDB_hickman_v001 Import Hickman et al. (2024) shape-tracing data.
%
% Returns a standardised trial struct array from the pre-processed
% baseData.mat files. Loads RAWDATA (60 Hz spline-resampled positions)
% for the ellipse shape (column 3, angular frequency 2) and optionally
% other shapes.
%
% USAGE:
%   trials = importDB_hickman_v001()
%   trials = importDB_hickman_v001(Study=1, Group="PDM0")
%   trials = importDB_hickman_v001(Study=2, Group="PLAC")
%   trials = importDB_hickman_v001(Study=1, Group="all", Shapes=3)
%
% INPUTS (name-value):
%   Study     - 1 (PD ON/OFF) or 2 (Haloperidol/Placebo). Default: 1.
%   Group     - Condition filter. Study 1: "PDM0"|"PDM1"|"all".
%               Study 2: "HALO"|"PLAC"|"all". Default: "all".
%   Shapes    - Shape column indices to extract. Default: 3 (ellipse).
%               [1=4/5, 2=4/3, 3=ellipse, 4=angfreq4]
%   Tasks     - (unused, for API consistency with importDB_cook_v002)
%   Verbose   - Print summary. Default: true.
%   DataRoot  - Path to data/hickman/. Default: auto-detect.
%
% OUTPUT:
%   trials    - struct array with fields: x, y, t, fs, subjectID,
%               trialID, condition, shape, database, notes,
%               units_verified, group, study
%
% NOTES:
%   - Positions are in Pavlovia pixel-equivalent units (normalised * 1200).
%     No mm conversion is applied. units_verified = false.
%   - Data were resampled from variable ~50 Hz to exactly 60 Hz via
%     spline in Hickman's Script1 preprocessing. dt = 1/60 exactly.
%   - The original Pavlovia CSV format stores mouse.x, mouse.y in
%     normalised coordinates [-1, 1]. Script1 scales by 1200.
%   - Study 1: PD patients ON (PDM1) vs OFF (PDM0) dopaminergic medication.
%   - Study 2: Healthy adults, haloperidol (HALO) vs placebo (PLAC).
%   - Pixel-to-mm conversion is an open decision (OD-17 in
%     TODO_Empirical_Validation.md). Beta is dimensionless and unaffected.
%
% PREREQ: Hickman's baseData.mat files must exist in data/hickman/Study N/.
%         These are generated by Hickman's Script1 from Pavlovia CSVs.
%
% SEE ALSO: importDB_cook_v002, importDB_zarandi_v001, importDB_dhieb_v001
%
% Fraser, D.S. (2026)

    arguments
        opts.Study    (1,1) double {mustBeMember(opts.Study, [1 2])} = 1
        opts.Group    (1,1) string = "all"
        opts.Shapes   (1,:) double = 3
        opts.Tasks    = []  % unused, API consistency
        opts.Verbose  (1,1) logical = true
        opts.DataRoot (1,1) string = ""
    end

    %% ---- Locate data directory ----
    if opts.DataRoot == ""
        thisFile = mfilename('fullpath');
        if ~isempty(thisFile)
            opts.DataRoot = fullfile(fileparts(fileparts(thisFile)), ...
                '..', 'data', 'hickman');
        else
            error('importDB_hickman:noRoot', ...
                'Cannot auto-detect DataRoot. Provide DataRoot explicitly.');
        end
    end

    studyDir = fullfile(opts.DataRoot, sprintf('Study %d', opts.Study));
    if ~isfolder(studyDir)
        error('importDB_hickman:noStudyDir', ...
            'Study directory not found: %s', studyDir);
    end

    %% ---- Determine condition file pairs ----
    if opts.Study == 1
        condMap = struct('prefix', {"PDM0", "PDM1"}, ...
                         'label',  {"PD_OFF", "PD_ON"});
        validGroups = ["PDM0", "PDM1", "all"];
    else
        condMap = struct('prefix', {"PLAC", "HALO"}, ...
                         'label',  {"Placebo", "Haloperidol"});
        validGroups = ["PLAC", "HALO", "all"];
    end

    if ~ismember(opts.Group, validGroups)
        error('importDB_hickman:badGroup', ...
            'Group must be one of: %s', strjoin(validGroups, ', '));
    end

    %% ---- Shape name mapping ----
    shapeNames = ["angfreq_4to5", "angfreq_4to3", "ellipse", "angfreq_4"];
    shapeFreq0 = [4/5, 4/3, 2, 4];

    %% ---- RAWDATA column indices (from rawCSVtoBaseData_func) ----
    col.time = 1;
    col.posX = 3;
    col.posY = 4;

    %% ---- Load and extract ----
    trials = [];
    nLoaded = 0;
    nEmpty = 0;

    for ci = 1:numel(condMap)
        if opts.Group ~= "all" && opts.Group ~= string(condMap(ci).prefix)
            continue
        end

        matFile = fullfile(studyDir, ...
            sprintf('%s-baseData.mat', condMap(ci).prefix));
        if ~isfile(matFile)
            warning('importDB_hickman:missingFile', ...
                'File not found: %s', matFile);
            continue
        end

        if opts.Verbose
            fprintf('Loading %s...\n', matFile);
        end

        S = load(matFile, 'OUT', 'RAWDATA');
        [nParticipants, nShapes, nTrials] = size(S.OUT);

        for si = 1:numel(opts.Shapes)
            shapeCol = opts.Shapes(si);
            if shapeCol < 1 || shapeCol > nShapes
                warning('importDB_hickman:badShape', ...
                    'Shape column %d out of range [1, %d]', shapeCol, nShapes);
                continue
            end

            for p = 1:nParticipants
                for t = 1:nTrials
                    if isempty(S.OUT{p, shapeCol, t}) || ...
                       isempty(S.RAWDATA{p, shapeCol, t})
                        nEmpty = nEmpty + 1;
                        continue
                    end

                    rd = S.RAWDATA{p, shapeCol, t};
                    outCell = S.OUT{p, shapeCol, t};

                    % Extract participant ID from filename prefix
                    expStr = string(outCell.Experiment);
                    pidMatch = regexp(expStr, '^\d+', 'match', 'once');
                    if isempty(pidMatch)
                        pidMatch = expStr;
                    end

                    % Validate minimum length
                    nSamp = size(rd, 1);
                    if nSamp < 100
                        nEmpty = nEmpty + 1;
                        continue
                    end

                    nLoaded = nLoaded + 1;
                    tr = struct();
                    tr.x          = rd(:, col.posX);
                    tr.y          = rd(:, col.posY);
                    tr.z          = [];
                    tr.t          = rd(:, col.time);
                    tr.fs         = 60;
                    tr.subjectID  = sprintf('S%s', pidMatch);
                    tr.trialID    = sprintf('S%s_%s_S%d_T%d', ...
                        pidMatch, condMap(ci).prefix, shapeCol, t);
                    tr.condition  = string(condMap(ci).label);
                    tr.shape      = shapeNames(shapeCol);
                    tr.database   = "hickman";
                    tr.notes      = sprintf('Study %d, %s, Freq0=%.4f', ...
                        opts.Study, condMap(ci).prefix, shapeFreq0(shapeCol));
                    tr.units_verified = false;
                    tr.group      = string(condMap(ci).prefix);
                    tr.study      = opts.Study;

                    if isempty(trials)
                        trials = tr;
                    else
                        trials(end+1) = tr; %#ok<AGROW>
                    end
                end
            end
        end
    end

    %% ---- Summary ----
    if opts.Verbose
        fprintf('\n=== importDB_hickman_v001 ===\n');
        fprintf('Study: %d\n', opts.Study);
        fprintf('Group filter: %s\n', opts.Group);
        fprintf('Shapes requested: %s (indices)\n', mat2str(opts.Shapes));
        fprintf('Trials loaded: %d\n', nLoaded);
        fprintf('Empty/short cells skipped: %d\n', nEmpty);
        if nLoaded > 0
            subjs = unique(string({trials.subjectID}));
            conds = unique(string({trials.condition}));
            durs = arrayfun(@(t) t.t(end) - t.t(1), trials);
            fprintf('Unique subjects: %d\n', numel(subjs));
            fprintf('Conditions: %s\n', strjoin(string(conds), ', '));
            fprintf('Duration: %.1f +/- %.1f s (range [%.1f, %.1f])\n', ...
                mean(durs), std(durs), min(durs), max(durs));
            fprintf('Sampling rate: %d Hz (spline-resampled)\n', trials(1).fs);
            fprintf('Position units: Pavlovia pixel-equivalent (NOT mm)\n');
        end
    end
end
