function plotEmpiricalCoverageHeatmap_v001()
% PLOTEMPIRICALCOVERAGEHEATMAP_V001  Replacement for Fig 6a.
%
% Builds an empirical invertibility coverage heatmap from the CURRENT
% (v012, genuine per-trial loop-closure) corpus and gate methodology
% (Finding #160), covering all seven canonical datasets including Fraser.
%
% Supersedes empiricalCoverage_v2_001.png, which was generated by the
% retired grid-snap methodology (checkInvertibilityForEmpirical_v2_00X.m,
% see its own header: "Snap (alpha, sigma_mm, fs, VGF) to simulation
% grid..."). That figure both omits Fraser and reports different
% per-cell coverage numbers to the ones the paper's own prose cites
% (Finding #160) -- the two were never the same computation.
%
% Identifiability aggregation here is IDENTICAL to compare42CellVerdict_
% v001.m (rise-coverage against results.invertStatus, PASS>=95%,
% CONDITIONAL>=90%, FAIL<90%, "no_beta_obs" trials excluded from the
% denominator) -- Finding #160's own methodology, not re-derived.
%
% ASSUMPTION CARRIED FROM compare42CellVerdict_v001.m, not independently
% verified here: invertStatus(pp) column order (pp=1..6) matches
% PIPELINES_NATIVE below. Each results .mat also stores its own
% `pipelineLabels` variable, which could be read and cross-checked
% against PIPELINES_NATIVE for an extra guard if this script is promoted
% beyond a one-off replacement figure.
%
% Fraser, D.S. (2026)

    srcDir = fileparts(mfilename('fullpath'));
    cd(srcDir);

    %% CONFIG ---------------------------------------------------------------
    % Native indexing order -- matches invertStatus(1:6) column convention
    % established by compare42CellVerdict_v001.m. Do not reorder without
    % re-checking that assumption against a dataset's own pipelineLabels.
    PIPELINES_NATIVE  = ["BWFD-OLS","SG-OLS","BWFD-LMLS","SG-LMLS","BWFD-IRLS","SG-IRLS"];
    % Paper's own display order (Methods Sec 2.2 pipeline table).
    PIPELINES_DISPLAY = ["BWFD-OLS","BWFD-LMLS","BWFD-IRLS","SG-OLS","SG-LMLS","SG-IRLS"];

    [foundMask, displayIdx] = ismember(PIPELINES_DISPLAY, PIPELINES_NATIVE);
    if ~all(foundMask)
        error('plotEmpiricalCoverageHeatmap:LabelMismatch', ...
            'PIPELINES_DISPLAY entries not found in PIPELINES_NATIVE.');
    end

    REGISTRY = struct( ...
        'name',   {'Zarandi','Cook CTRL','Cook ASD','Dhieb','Hickman PLAC','Hickman HALO','Fraser'}, ...
        'matTag', {'Zarandi','Cook_CTRL','Cook_ASD','Dhieb','Hickman_PLAC','Hickman_HALO','Fraser'});
    nDS = numel(REGISTRY);
    nPP = numel(PIPELINES_NATIVE);

    %% Load real v012 corpora -------------------------------------------
    fprintf('Loading v012 loop-closure corpora (7 datasets)...\n');
    coverageGrid = NaN(nDS, nPP);
    verdictGrid  = strings(nDS, nPP);

    for d = 1:nDS
        matFile = sprintf('loopClosureResults_%s_all_shaped_xu_v012.mat', REGISTRY(d).matTag);
        if ~isfile(matFile)
            error('plotEmpiricalCoverageHeatmap:NoLoopClosureFile', ...
                'FAILED PATH: %s not found in %s.', matFile, srcDir);
        end
        Dset = load(matFile, 'results');
        for p = 1:nPP
            statuses = arrayfun(@(r) r.invertStatus(p), Dset.results);
            valid  = statuses ~= "no_beta_obs";
            nValid = sum(valid);
            if nValid == 0
                verdictGrid(d,p) = "no-data";
                continue
            end
            cov = sum(statuses(valid) == "rise") / nValid;
            coverageGrid(d,p) = cov;
            if cov >= 0.95
                verdictGrid(d,p) = "PASS";
            elseif cov >= 0.90
                verdictGrid(d,p) = "CONDITIONAL";
            else
                verdictGrid(d,p) = "FAIL";
            end
        end
    end

    % Fail loud, not silent: cross-check against Finding #160's own split.
    nPass = sum(verdictGrid(:) == "PASS");
    nCond = sum(verdictGrid(:) == "CONDITIONAL");
    nFail = sum(verdictGrid(:) == "FAIL");
    fprintf('\nRecomputed 42-cell split: %d PASS + %d CONDITIONAL + %d FAIL  (Finding #160: 4+6+32)\n', ...
        nPass, nCond, nFail);
    if ~isequal([nPass nCond nFail], [4 6 32])
        warning('plotEmpiricalCoverageHeatmap:VerdictMismatch', '%s', sprintf([ ...
            'Recomputed split does not match Finding #160''s reported 4+6+32. ' ...
            'Do not silently trust this figure -- check dataset/pipeline order and ' ...
            'mat versions against compare42CellVerdict_v001.m before using it.']));
    end

    %% Reorder to the paper's display convention -------------------------
    coverageDisp = coverageGrid(:, displayIdx);
    verdictDisp  = verdictGrid(:, displayIdx);

    verdictCode = zeros(nDS, numel(PIPELINES_DISPLAY));
    verdictCode(verdictDisp == "FAIL")        = 1;
    verdictCode(verdictDisp == "CONDITIONAL") = 2;
    verdictCode(verdictDisp == "PASS")        = 3;
    % (0 = no-data, left at default)

    %% Figure -------------------------------------------------------------
    fig = figure('Name', 'Empirical invertibility coverage (v012)', 'Position', [80 80 950 560]);
    ax = axes(fig);

    cmap = [0.85 0.85 0.85;   % 0 = no-data (grey)
            0.80 0.25 0.25;   % 1 = FAIL (red)
            0.90 0.65 0.15;   % 2 = CONDITIONAL (amber)
            0.25 0.60 0.30];  % 3 = PASS (green)
    imagesc(ax, verdictCode);
    colormap(ax, cmap);
    clim(ax, [0 3]);

    ax.XTick = 1:numel(PIPELINES_DISPLAY);
    ax.XTickLabel = PIPELINES_DISPLAY;
    ax.XTickLabelRotation = 30;
    ax.YTick = 1:nDS;
    ax.YTickLabel = {REGISTRY.name};

    for d = 1:nDS
        for p = 1:numel(PIPELINES_DISPLAY)
            if isnan(coverageDisp(d,p))
                lbl = 'n/a';
            else
                lbl = sprintf('%.1f%%', 100*coverageDisp(d,p));
            end
            text(ax, p, d, lbl, 'HorizontalAlignment', 'center', ...
                'Color', [1 1 1], 'FontWeight', 'bold', 'FontSize', 9);
        end
    end

    title(ax, { ...
        'Empirical invertibility coverage -- v012 loop-closure gate (Finding #160)', ...
        'Red = FAIL (<90%), Amber = CONDITIONAL (90-95%), Green = PASS (>=95%) rising-branch coverage'}, ...
        'FontSize', 10);

    %% Save
    outFile = fullfile('..', 'figures', 'empiricalCoverageHeatmap_v001.png');
    saveas(fig, outFile);
    fprintf('\nSaved: %s\n', outFile);

end
